import { describe, expect, it, vi } from 'vitest';
import fixtures from './fixtures/v1-canonical.json';
import { canonicalBytes, snapshotId } from './canonical';
import { PublicExportConsumer, FETCH_INTERVAL_MS, TTL_MS } from './consumer';
import { TrustBundle, trustBundleFromBuildJson } from './trustBundle';
import { FetchTransport, FileTransport, type PublicExportTransport } from './transport';

const now = Date.parse('2026-09-18T12:00:00.000Z');
const iso = (time: number) => new Date(time).toISOString();
const text = (bytes: Uint8Array) => new TextDecoder().decode(bytes);

function record(name = 'کافهٔ واقعی', coords: [number | null, number | null] = [35.123456, 51.123456]) {
  return {
    business: {
      organization_id: 'org-1', name, description: 'شرح عمومی',
      location: { latitude: coords[0], longitude: coords[1], address_text: 'تهران' },
      contact_information: { public_phone: '021000', public_email: 'public@example.test', public_address: 'تهران' },
      links: { website: 'https://example.test', public_social: ['https://example.test/social'] },
      business_hours: { schema_version: 'mlino.business-hours.v1', timezone: 'UTC', weekly: [] },
      published_at: iso(now - 60_000), publication_id: 'publication-profile', source_revision: 2,
    },
    capabilities: [{ capability_id: 'cap-1', capability_key: 'service', name: 'خدمت', short_description: null,
      fresh_until: iso(now + 10_000), source_revision: 3 }],
    offers: [{ offer_id: 'offer-1', offer_version_id: 'version-1', version_number: 1,
      name: 'پیشنهاد', short_description: 'توضیح', offer_shape: 'FIXED_PRICE',
      terms: { schema_version: 'mlino.offer-terms.v1', summary: 'شرایط', conditions: [] },
      price_amount: '100.00', price_currency: 'IRR', on_request: false,
      valid_from: iso(now - 60_000), valid_until: iso(now + 10_000),
      capability_links: [{ capability_id: 'cap-1', capability_key: 'service', name: 'خدمت' }],
      published_at: iso(now - 50_000), publication_id: 'publication-offer' }],
    stale: false, ordering: { primary: 'publication.occurred_at', tie_breaker: 'publication.id' },
  };
}

async function keyPair() {
  const pair = await crypto.subtle.generateKey('Ed25519', true, ['sign', 'verify']);
  const publicKey = new Uint8Array(await crypto.subtle.exportKey('raw', pair.publicKey));
  return { pair, publicKey, trust: new TrustBundle('test-v1', [{ keyId: 'test-key', rawPublicKey: publicKey }]) };
}

async function signed(pair: CryptoKeyPair, records: unknown[] = [record()], generatedAt = now, algorithm = 'Ed25519'): Promise<Uint8Array> {
  const unsigned = { contract_version: 'mlino.v2.public-business.v1', generated_at: iso(generatedAt),
    snapshot_id: await snapshotId('mlino.v2.public-business.v1', records), records };
  const signature = { algorithm, key_id: 'test-key' };
  const signedContent = canonicalBytes({ ...unsigned, signature });
  const prefix = new TextEncoder().encode('MLINO-PUBLIC-BUSINESS-V1\n');
  const input = new Uint8Array(prefix.length + signedContent.length);
  input.set(prefix); input.set(signedContent, prefix.length);
  const value = new Uint8Array(await crypto.subtle.sign('Ed25519', pair.privateKey, input as BufferSource));
  const base64url = btoa(String.fromCharCode(...value)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  return canonicalBytes({ ...unsigned, signature: { ...signature, value: base64url } });
}

describe('V1 canonical byte parity', () => {
  it.each(fixtures)('$name matches bytes and sha256 generated by origin/main V1', async (fixture) => {
    const input = fixture.name === 'negative_zero' ? { zero: -0 } : fixture.input;
    const actual = canonicalBytes(input);
    expect(Array.from(actual, (byte) => byte.toString(16).padStart(2, '0')).join('')).toBe(fixture.expected_hex);
    const hash = new Uint8Array(await crypto.subtle.digest('SHA-256', new Uint8Array(actual) as BufferSource));
    expect(Array.from(hash, (byte) => byte.toString(16).padStart(2, '0')).join('')).toBe(fixture.expected_sha256);
  });
  it('rejects lone surrogates and values beyond six decimal places', () => {
    expect(() => canonicalBytes({ text: '\ud800' })).toThrow('PUBLIC_EXPORT_INVALID_UNICODE');
    expect(() => canonicalBytes({ number: 0.1234567 })).toThrow('PUBLIC_EXPORT_NUMBER_PRECISION');
  });
});

describe('signed public export consumer', () => {
  it('C8-1 accepts the same signed bytes through pluggable file and fetch ports without a network call', async () => {
    const { pair, trust } = await keyPair();
    const bytes = await signed(pair);
    const file = new PublicExportConsumer(new FileTransport(bytes), trust);
    const fetchStub = vi.fn(async () => new Response(new Uint8Array(bytes) as BodyInit));
    vi.stubGlobal('fetch', fetchStub);
    try {
      const fetched = new PublicExportConsumer(new FetchTransport('/public-business.v1.json'), trust);
      await file.refresh(now);
      await fetched.refresh(now);
      expect(fetched.read(now)).toEqual(file.read(now));
      expect(fetchStub).toHaveBeenCalledTimes(1);
    } finally { vi.unstubAllGlobals(); }
  });

  it('accepts a valid artifact and maps every public field without draft-1 inventions', async () => {
    const { pair, trust } = await keyPair();
    const transport = new FileTransport(await signed(pair));
    const consumer = new PublicExportConsumer(transport, trust);
    await consumer.refresh(now);
    const [item] = consumer.read(now);
    expect(item.business).toMatchObject({ organization_id: 'org-1', name: 'کافهٔ واقعی', description: 'شرح عمومی',
      source_revision: 2, publication_id: 'publication-profile', contact_information: { public_phone: '021000' } });
    expect(item.business.location).toEqual({ latitude: 35.123456, longitude: 51.123456, address_text: 'تهران' });
    expect(item.business.business_hours).toMatchObject({ schema_version: 'mlino.business-hours.v1' });
    expect(item.business.links).toMatchObject({ website: 'https://example.test' });
    expect(item.capabilities[0]).toMatchObject({ capability_id: 'cap-1', capability_key: 'service', source_revision: 3 });
    expect(item.offers[0]).toMatchObject({ offer_version_id: 'version-1', price_amount: '100.00', on_request: false,
      terms: { schema_version: 'mlino.offer-terms.v1' }, capability_links: [{ capability_id: 'cap-1' }] });
    for (const absent of ['category', 'floor_level', 'building_id', 'products', 'discount_percent']) {
      expect(JSON.stringify(item)).not.toContain(`"${absent}"`);
    }
    expect(consumer.findNear(35.123456, 51.123456, 100, now)).toHaveLength(1);
  });

  it('rejects a one-byte content tamper and keeps the prior valid cache', async () => {
    const { pair, trust } = await keyPair();
    const transport = new FileTransport(await signed(pair));
    const consumer = new PublicExportConsumer(transport, trust);
    await consumer.refresh(now);
    const tampered = text(await signed(pair, [record('دیگر')], now + 1000)).replace('دیگر', 'دیکر');
    transport.replace(new TextEncoder().encode(tampered));
    await expect(consumer.refresh(now + 1000)).rejects.toThrow('PUBLIC_EXPORT_BAD_SIGNATURE');
    expect(consumer.read(now + 1000)[0].business.name).toBe('کافهٔ واقعی');
    expect(consumer.read(now + TTL_MS + 1)).toEqual([]);
  });

  it('rejects unknown and revoked key ids with their exact error code', async () => {
    const { pair, publicKey, trust } = await keyPair();
    const bytes = await signed(pair);
    const unknown = new TextEncoder().encode(text(bytes).replace('test-key', 'other-key'));
    await expect(new PublicExportConsumer(new FileTransport(unknown), trust).refresh(now)).rejects.toThrow('PUBLIC_EXPORT_UNKNOWN_OR_REVOKED_KEY');
    const revoked = new TrustBundle('test-v2', [{ keyId: 'test-key', rawPublicKey: publicKey }], ['test-key']);
    await expect(new PublicExportConsumer(new FileTransport(bytes), revoked).refresh(now)).rejects.toThrow('PUBLIC_EXPORT_UNKNOWN_OR_REVOKED_KEY');
    const parsed = JSON.stringify({ version: 'built-v1', keys: [{ keyId: 'test-key', rawPublicKeyBase64Url: btoa(String.fromCharCode(...publicKey)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '') }], revokedIds: ['test-key'] });
    expect(trustBundleFromBuildJson(parsed).publicKey('test-key')).toBeNull();
  });

  it('rejects a non-Ed25519 algorithm even when its declared bytes have a valid Ed25519 signature', async () => {
    const { pair, trust } = await keyPair();
    const bytes = await signed(pair, [record()], now, 'Ed448');
    await expect(new PublicExportConsumer(new FileTransport(bytes), trust).refresh(now)).rejects.toThrow('PUBLIC_EXPORT_SIGNATURE_SHAPE');
  });

  it.each([
    ['non-base64url character', '+'],
    ['wrong decoded length', 'AA'],
    ['non-canonical trailing bits', 'AB'],
  ])('rejects a signature value with %s', async (_case, value) => {
    const { pair, trust } = await keyPair();
    const artifact = JSON.parse(text(await signed(pair))) as Record<string, unknown>;
    const signature = artifact.signature as Record<string, unknown>;
    signature.value = value;
    const bytes = canonicalBytes(artifact);
    await expect(new PublicExportConsumer(new FileTransport(bytes), trust).refresh(now)).rejects.toThrow('PUBLIC_EXPORT_SIGNATURE_VALUE');
  });

  it('C8-2 and N1 use the supplied device clock for TTL, skew and ordering', async () => {
    const { pair, trust } = await keyPair();
    expect(FETCH_INTERVAL_MS).toBe(60_000);
    await expect(new PublicExportConsumer(new FileTransport(await signed(pair, [record()], now - TTL_MS - 1)), trust).refresh(now)).rejects.toThrow('PUBLIC_EXPORT_EXPIRED_OR_FUTURE');
    await expect(new PublicExportConsumer(new FileTransport(await signed(pair, [record()], now + 30_001)), trust).refresh(now)).rejects.toThrow('PUBLIC_EXPORT_EXPIRED_OR_FUTURE');
    const transport = new FileTransport(await signed(pair));
    const consumer = new PublicExportConsumer(transport, trust);
    await consumer.refresh(now);
    transport.replace(await signed(pair, [record('قدیمی')], now - 1));
    await expect(consumer.refresh(now)).rejects.toThrow('PUBLIC_EXPORT_OLDER');
    transport.replace(await signed(pair, [record('هم‌زمان')], now));
    await expect(consumer.refresh(now)).rejects.toThrow('PUBLIC_EXPORT_OLDER');
    expect(consumer.read(now)[0].business.name).toBe('کافهٔ واقعی');
  });

  it('starts empty and never accepts draft-1 mock as a real fallback', async () => {
    const { trust } = await keyPair();
    const consumer = new PublicExportConsumer(new FileTransport(new TextEncoder().encode('{"contract_version":"draft-1"}')), trust);
    expect(consumer.read(now)).toEqual([]);
    await expect(consumer.refresh(now)).rejects.toThrow('PUBLIC_EXPORT_VERSION');
    expect(consumer.read(now)).toEqual([]);
  });

  it('N2 does not accept trust keys injected by the artifact itself', async () => {
    const { pair, trust } = await keyPair();
    const raw = await signed(pair);
    const injected = text(raw).replace('"key_id":"test-key"', '"key_id":"test-key","public_key":"injected"');
    await expect(new PublicExportConsumer(new FileTransport(new TextEncoder().encode(injected)), trust).refresh(now)).rejects.toThrow('PUBLIC_EXPORT_SIGNATURE_SHAPE');
    expect(() => trustBundleFromBuildJson(JSON.stringify({ version: 'test', keys: [], revokedIds: [], privateKey: 'forbidden' }))).toThrow('TRUST_BUNDLE_SHAPE');
  });

  it('C8-5 removes a suspended business on the next accepted cycle, not before', async () => {
    const { pair, trust } = await keyPair();
    const transport = new FileTransport(await signed(pair));
    const consumer = new PublicExportConsumer(transport, trust);
    await consumer.refresh(now);
    expect(consumer.read(now)).toHaveLength(1);
    transport.replace(await signed(pair, [], now + 1000));
    expect(consumer.read(now + 1000)).toHaveLength(1);
    await consumer.refresh(now + 1000);
    expect(consumer.read(now + 1000)).toHaveLength(0);
  });

  it('rejects links outside the same record and excludes null coordinates from proximity', async () => {
    const { pair, trust } = await keyPair();
    const noPoint = record('بی‌مختصات', [null, null]);
    const transport = new FileTransport(await signed(pair, [noPoint]));
    const consumer = new PublicExportConsumer(transport, trust);
    await consumer.refresh(now);
    expect(consumer.read(now)).toHaveLength(1);
    expect(consumer.findNear(35, 51, 5000, now)).toEqual([]);
    const invalid = record();
    invalid.offers[0].capability_links[0].capability_id = 'other-record';
    transport.replace(await signed(pair, [invalid], now + 1000));
    await expect(consumer.refresh(now + 1000)).rejects.toThrow('PUBLIC_EXPORT_INVALID_CAPABILITY_LINK');
  });

  it('filters capability and offer expiry again at read time', async () => {
    const { pair, trust } = await keyPair();
    const consumer = new PublicExportConsumer(new FileTransport(await signed(pair)), trust);
    await consumer.refresh(now);
    expect(consumer.read(now)[0].capabilities).toHaveLength(1);
    expect(consumer.read(now)[0].offers).toHaveLength(1);
    expect(consumer.read(now + 10_001)[0].capabilities).toHaveLength(0);
    expect(consumer.read(now + 10_001)[0].offers).toHaveLength(0);
  });

  it('swaps one snapshot reference after verification while in-flight reads stay consistent', async () => {
    const { pair, trust } = await keyPair();
    let release: ((bytes: Uint8Array) => void) | undefined;
    const first = await signed(pair);
    const second = await signed(pair, [record('نسخهٔ دوم')], now + 1000);
    let next = false;
    const transport: PublicExportTransport = { read: () => next ? new Promise<Uint8Array>((resolve) => { release = resolve; }) : Promise.resolve(first) };
    const consumer = new PublicExportConsumer(transport, trust);
    await consumer.refresh(now);
    const held = consumer.read(now);
    next = true;
    const pending = consumer.refresh(now + 1000);
    expect(consumer.read(now + 1000)[0].business.name).toBe('کافهٔ واقعی');
    release!(second);
    await pending;
    expect(held[0].business.name).toBe('کافهٔ واقعی');
    expect(consumer.read(now + 1000)[0].business.name).toBe('نسخهٔ دوم');
  });
});
